### ISSUE TITLE
New analytics rule gets deleted when you view the rule in the UI after docker restart  

### ISSUE THREAD

**Issue by PS222407** [bfritscher/typesense-dashboard#69]
**Describe the bug**
It seems like when you create a rule, restart the docker container and view the new rule in the UI before using shell it gets deleted. I think only when source and destination are the same collection but I could not verify that bit for sure.

**To Reproduce**

1. docker-compose.yml
```
services:
  typesense:
    image: typesense/typesense:27.0.rc29
    container_name: test-typesense
    restart: on-failure
    volumes:
      - ./typesense-data-dir:/data
    ports:
      - 8108:8108
    command: '--data-dir /data --api-key=xyz --enable-cors --cors-domains=http://localhost:8188 --enable-search-analytics=true --analytics-dir=/data/analytics --analytics-flush-interval=60'

  typesense_dashboard:
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    container_name: test-typesense_dashboard
    restart: on-failure
    volumes:
      - ./typesense-dashboard/config.json:/srv/config.json
    ports:
      - 8188:80
```
`docker-compose up -d`
2. create collection
```
curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: xyz" \
       -d '{
         "name": "product_variants",
         "fields": [
           {"name": "name", "type": "string" },
           {"name": "popularity", "type": "int32" }
         ],
         "default_sorting_field": "popularity"
       }'
```

3. insert a document
```
curl "http://localhost:8108/collections/product_variants/documents" -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: xyz" \
        -d '{
          "id": "1",
          "name": "First test product",
          "popularity": 0
        }'
```

4. create a rule
```
curl -k "http://localhost:8108/analytics/rules" \
      -X POST \
      -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: xyz" \
      -d '{
        "name": "product_variants_popularity",
        "type": "counter",
        "params": {
            "source": {
                "collections": ["product_variants"],
                "events":  [
                    {"type": "click", "weight": 1, "name": "product_variants_click_event"}
                ]
            },
            "destination": {
                "collection": "product_variants",
                "counter_field": "popularity"
            }
        }
      }'
```

5. restart docker containers
docker-compose down && docker-compose up -d

**Expected behavior**
It should display the earlier created rule.

**Environment (please complete the following information):**
 - Application mode: Web
 - OS: [Ubuntu 24.04 in WSL2 on Windows 11]
 - Browser: [chrome]
 - Version: [1.9.1]
- Typesense Server version: [27.0.rc29 or 26.0]
